export const calculatorButtons = [
  { id: "ac", label: "AC", value: "AC", variant: "secondary" },
  { id: "back", label: "⌫", value: "BACK", variant: "secondary" },
  { id: "percent", label: "%", value: "%", variant: "secondary" },
  { id: "divide", label: "÷", value: "÷", variant: "operator" },
  { id: "seven", label: "7", value: "7", variant: "digit" },
  { id: "eight", label: "8", value: "8", variant: "digit" },
  { id: "nine", label: "9", value: "9", variant: "digit" },
  { id: "multiply", label: "×", value: "×", variant: "operator" },
  { id: "four", label: "4", value: "4", variant: "digit" },
  { id: "five", label: "5", value: "5", variant: "digit" },
  { id: "six", label: "6", value: "6", variant: "digit" },
  { id: "minus", label: "-", value: "-", variant: "operator" },
  { id: "one", label: "1", value: "1", variant: "digit" },
  { id: "two", label: "2", value: "2", variant: "digit" },
  { id: "three", label: "3", value: "3", variant: "digit" },
  { id: "plus", label: "+", value: "+", variant: "operator" },
  { id: "toggle", label: "±", value: "TOGGLE_SIGN", variant: "secondary" },
  { id: "zero", label: "0", value: "0", variant: "digit", size: "wide" },
  { id: "decimal", label: ".", value: ".", variant: "digit" },
  { id: "equals", label: "=", value: "=", variant: "equal" },
];
